// export celebrities array
module.exports = {
  exportCeleb: () => {
    return celebrities;
  },
};

// Celebrities list
const celebrities = [
  {
    name: 'Isaac Newton',
    fictional: false,
    born: 1643,
    died: 1727,
    centuries: [17, 18],
    sex: 'male',
    land: 'Eurasia',
    continent: 'Europe',
    country:'England',
    language: 'English',
    coasts: true,
    peninsular: false,
    sea: 'North',
    mainField: 'science',
    fields: ['mathematician', 'astronomer', 'theologian', 'author', 'physicist'],
    akas: ['Isaac Newton', 'Newton'],
  },
  {
    name: 'Abraham Lincoln',
    fictional: false,
    born: 1809,
    died: 1865,
    centuries: [19],
    sex: 'male',
    land: 'America',
    latinAmerica: false,
    continent: 'North America',
    country:'United States',
    language: 'English',
    mainField: 'politics',
    fields: ['lawyer', 'politician'],
    akas: ['Abraham Lincoln', 'Lincoln'],
  },
  {
    name: 'Mario Benedetti',
    fictional: false,
    born: 1920,
    died: 2009,
    centuries: [20, 21],
    sex: 'male',
    land: 'America',
    latinAmerica: true,
    continent: 'South America',
    country:'Uruguay',
    language: 'Spanish',
    mainField: 'arts',
    plasticArts: false,
    performing: false,
    music: false,
    literature: true,
    dance: false,
    fields: ['journalist', 'novelist', 'poet', 'writer'],
    akas: ['Mario Benedetti', 'Benedetti'],
  },
  {
    name: 'Mercedes Sosa',
    fictional: false,
    born: 1935,
    died: 2009,
    centuries: [20, 21],
    sex: 'female',
    land: 'America',
    latinAmerica: true,
    continent: 'South America',
    country:'Argentina',
    language: 'Spanish',
    mainField: 'arts',
    plasticArts: false,
    performing: false,
    music: true,
    literature: false,
    dance: false,
    fields: ['singer', 'musician'],
    akas: ['Mercedes Sosa', 'La Negra'],
  },
  {
    name: 'Gabriel Garcia Marquez',
    fictional: false,
    born: 1927,
    died: 2014,
    centuries: [20, 21],
    sex: 'male',
    land: 'America',
    latinAmerica: true,
    continent: 'South America',
    country:'Colombia',
    language: 'Spanish',
    mainField: 'arts',
    plasticArts: false,
    performing: false,
    music: false,
    literature: true,
    dance: false,
    fields: ['writer', 'novelist','sreenwriter', 'journalist'],
    akas: ['Gabriel Garcia Marquez', 'Garcia Marquez', 'Gabo'],
  },
  {
    name: 'Mario Moreno',
    fictional: false,
    born: 1911,
    died: 1993,
    centuries: [20],
    sex: 'male',
    land: 'America',
    latinAmerica: true,
    continent: 'North America',
    country:'Mexico',
    language: 'Spanish',
    mainField: 'arts',
    plasticArts: false,
    performing: true,
    music: false,
    literature: false,
    dance: false,
    fields: ['actor', 'comedian','sreenwriter', 'producer'],
    akas: ['Mario Moreno', 'Cantinflas'],
  },
  {
    name: 'Jose Marti',
    fictional: false,
    born: 1853,
    died: 1895,
    centuries: [19],
    sex: 'male',
    land: 'America',
    latinAmerica: true,
    continent: 'Central America and the Caribbean',
    country:'Cuba',
    language: 'Spanish',
    island: true, // not really is an archipelago
    mainField: ['arts', 'politics'], // usually a string, here an array. Use Array.isArray();
    plasticArts: false,
    performing: false,
    music: false,
    literature: true,
    dance: false,
    fields: ['writer', 'poet','assyist', 'journalist', 'translator', 'philosopher', 'theorist'],
    akas: ['Jose Marti', 'Marti', 'El apostol', 'The apostle'],
  },
  {
    name: 'Miguel de Cervantes y Saavedra',
    fictional: false,
    born: 1547,
    died: 1616,
    centuries: [16, 17],
    sex: 'male',
    land: 'Eurasia',
    continent: 'Europe',
    country:'Spain',
    language: 'Spanish',
    coasts: true,
    peninsular: true,
    sea: 'Mediterranean',
    mainField: 'arts',
    plasticArts: false,
    performing: false,
    music: false,
    literature: true,
    dance: false,
    fields: ['writer', 'novelist'],
    akas: ['Miguel de Cervantes y Saavedra', 'Miguel de Cervantes', 'Miguel Cervantes', 'Cervantes', 'El manco de Lepanto'],
  },
  {
    name: 'Luciano Pavarotti',
    fictional: false,
    born: 1935,
    died: 2007,
    centuries: [20, 21],
    sex: 'male',
    land: 'Eurasia',
    continent: 'Europe',
    country:'Italy',
    language: 'Italian',
    coasts: true,
    peninsular: true,
    sea: ['Mediterranean', 'Adriatic'], // usually a string, here an array. Use Array.isArray();
    mainField: 'arts',
    plasticArts: false,
    performing: true,
    music: true,
    literature: false,
    dance: false,
    fields: ['writer', 'novelist'],
    akas: ['Miguel de Cervantes y Saavedra', 'Miguel de Cervantes', 'Miguel Cervantes', 'Cervantes', 'El manco de Lepanto'],
  },
  {
    name: 'Marie Curie',
    fictional: false,
    born: 1867,
    died: 1934,
    centuries: [19, 20],
    sex: 'female',
    land: 'Eurasia',
    continent: 'Europe',
    country:'France',
    language: 'French',
    coasts: true,
    peninsular: false,
    sea: 'Mediterranean',
    mainField: 'science',
    fields: ['physicist', 'chemist'],
    akas: ['Marie Sklodowska Curie', 'Maria Salomea Sklodowska', 'Marie Curie', 'Maria Curie'],
  },
]




